name: shop_app
description: "A new Flutter project."


publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  cloud_firestore: ^5.6.9
  font_awesome_flutter: ^10.8.0
  lottie: ^3.3.1
  dots_indicator: ^4.0.1
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  flutter_screenutil: ^5.9.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/anims/
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-ExtraBold.otf
          weight: 900
        - asset: assets/fonts/Gilroy-Light.otf
          weight: 300
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300